merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("band/", views.bands, name='band-list'),
    path('band/<int:id>/', views.band_detail, name='band-detail'),
    path('band/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('band/add/', views.band_create, name='band-create'),
    path('band/<int:id>/change/', views.band_update, name='band-update'),
    path("contact-us/", views.contact, name='contact'),
    path("listing/", views.listings, name='listing-list'),
    path("listing/<int:id>/", views.listing_detail, name='listing-detail'),
    path("listing/<int:id>/delete/", views.listing_delete, name='listing-delete'),
    path('listing/add/', views.listing_create, name='listing-create'),
    path("listing/<int:id>/change/", views.listing_update, name='listing-update'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2025)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):

    class Type(models.TextChoices):
        RECORDS = 'Records',
        CLOTHING = 'Clothing',
        POSTERS = 'Posters',
        MISCELLANEOUS = 'Miscellaneous',

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=300)
    is_sold = models.fields.BooleanField(default=False)
    year_formed = models.fields.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(1900), MaxValueValidator(2025)]
    )
    type = models.fields.CharField(choices=Type.choices, max_length=20)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.http import Http404
from django.shortcuts import render
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect

# Create your views here.
def home(request):
    return render(
        request,
        'listings/base.html',
    )

def bands(request):
    band_list = Band.objects.all()
    return render(
        request,
        'listings/band_list.html',
        {'band_list': band_list}
    )

# listings/views.py

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request,
            'listings/band_create.html',
            {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_update.html',
                {'form': form})

def band_detail(request, id):
    try:
        band = Band.objects.get(id=id)
    except Band.DoesNotExist:
        raise Http404("Band does not exist")
    return render(
        request,
        'listings/band_detail.html',
        {'band': band}
    )

def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})

def about(request):
    return render(request, 'listings/about.html')

def listings(request):
    listing_list = Listing.objects.all()
    return render(
        request,
        'listings/listing_list.html',
        {'listing_list': listing_list},
    )

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm()

    return render(request,
            'listings/listing_create.html',
            {'form': form})

def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                'listings/listing_update.html',
                {'form': form})

def listing_detail(request, id):
    try:
        listing = Listing.objects.get(id=id)
    except Listing.DoesNotExist:
        raise Http404("Listing does not exist")
    return render(
        request,
        'listings/listing_detail.html',
        {'listing': listing}
    )

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        listing.delete()
        # rediriger vers la liste des groupes
        return redirect('listing-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/listing_delete.html',
                    {'listing': listing})

def contact(request):
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
        # return redirect('email-sent')
    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

    else:
    # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()

    return render(
        request,
        'listings/contact.html',
        {'form': form}
    )

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %} {% block content %}
<h1>A propos</h1>
<p>Nous adorons merch!</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %} {% block content %}
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer" />
</form>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %} {% block content %}

<h2>{{ band.name }}</h2>

<ul>
  <li>Genre : {{ band.get_genre_display }}</li>
  <li>Année de formation : {{ band.year_formed }}</li>
  <li>Actif : {{ band.active|yesno }}</li>
  {% if band.official_homepage %}
  <li>
    <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a>
  </li>
  {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-list' %}">Retour à la liste</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
  {% for band in band_list %}
  <li>
    <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a> -
    <a href="{% url 'band-update' band.id %}">[modifier]</a>
    <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
  <head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
      <div class="container-fluid">
        <div class="col">
          <a class="navbar-brand" href="{% url 'band-list' %}">Groupes</a>
          <a class="navbar-brand" href="{% url 'listing-list' %}">Listing</a>
        </div>
        <div class="col d-flex">
          <a class="navbar-brand" href="{% url 'contact' %}">Contact</a>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %} {% block content %}
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Créer un nouveau listing</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %} {% block content %}
<h1>Supprimer le listing</h1>

<p>Etes-vous sûr de vouloir supprimer le listing : {{ listing.title }} ?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer" />
</form>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %} {% block content %}

<h2>{{ listing.title }}</h2>

<ul>
  <li>Description : {{ listing.description }}</li>
  <li>Année de formation : {{ listing.year_formed }}</li>
  <li>Vendu ? : {{ listing.is_sold|yesno }}</li>
  <li>Type : {{ listing.type }}</li>
</ul>

<p>{{ listing.band }}</p>

<a href="{% url 'listing-update' listing.id %}">Modifier ce listing</a>

<a href="{% url 'listing-list' %}">Retour à la liste</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %} {% block content %}
<h1>Listing</h1>
<a href="{% url 'listing-create' %}">Créer un nouveau listing</a>
<ul>
  {% for listing in listing_list %}
  <li>
    <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a> -
    <a href="{% url 'listing-update' listing.id %}">[modifier]</a>
    <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Modifier un listing</h1>

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Envoyer" />
</form>

{% endblock %}